from __future__ import annotations

import json
import hashlib
import os
from pathlib import Path

from fast_gen.plan import render_template

GENERATOR = "fastapi-codegen"
PACKAGE_INIT = '"""Generated module package."""\n'


def repo_root() -> Path:
  target = os.environ.get("CODEGENKIT_ROOT")
  if not target:
    raise RuntimeError("CODEGENKIT_ROOT is required for the FastAPI adapter")
  return Path(target).resolve()


def _sha256(content: str) -> str:
  return hashlib.sha256(content.encode("utf-8")).hexdigest()


def _package_version() -> str:
  package_json = Path(__file__).resolve().parents[5] / "package.json"
  return str(json.loads(package_json.read_text(encoding="utf-8"))["version"])


def _safe_target(root: Path, relative_path: str) -> Path:
  relative = Path(relative_path)
  if relative.is_absolute() or ".." in relative.parts:
    raise ValueError(f"Unsafe generated path (absolute or traversal): {relative_path}")
  target = root / relative
  if os.path.commonpath((str(root), str(target))) != str(root):
    raise ValueError(f"Generated path escapes CODEGENKIT_ROOT: {relative_path}")
  _reject_symlinks(target, root)
  return target


def _reject_symlinks(target: Path, boundary: Path | None = None) -> None:
  current = target
  stop = boundary.parent if boundary is not None else Path(current.anchor)
  while current != stop:
    if current.is_symlink():
      raise ValueError(f"Unsafe symlink in output path: {current}")
    current = current.parent


def _router_content(contexts: list[dict], existing: str = "") -> str:
  imports = {
    line
    for line in existing.splitlines()
    if line.startswith("from app.modules.") and " import " in line
  }
  for ctx in contexts:
    imports.add(
      f"from app.modules.{ctx['module_package']}.{ctx['entity_snake']}.router import "
      f"router as {ctx['module_package']}_{ctx['entity_snake']}_router"
    )
  ordered = sorted(imports)
  aliases = [line.split(" as ")[-1].strip() for line in ordered]
  return "\n".join([
    '"""Auto-generated by fast-gen — do not edit manually."""',
    "",
    "from fastapi import APIRouter",
    "",
    *ordered,
    "",
    "ROUTERS: list[APIRouter] = [",
    *[f"  {alias}," for alias in aliases],
    "]",
    "",
  ])


def _planned_outputs(plan: dict) -> list[dict]:
  root = repo_root()
  outputs: list[dict] = []
  for file in plan["files"]:
    outputs.append({
      **file,
      "content": render_template(file["template"], file["ctx"]),
    })
  for ctx in plan["contexts"]:
    base = Path("src/app/modules") / ctx["module_package"] / ctx["entity_snake"]
    for folder in [base.parent, base, base / "schemas", base / "services", base / "presenters"]:
      outputs.append({
        "relativePath": str(folder / "__init__.py"),
        "content": PACKAGE_INIT,
        "template": "package-init",
        "layer": "package",
        "entity": ctx["entity"],
        "module": ctx["module"],
      })
  unique: dict[str, dict] = {}
  for output in outputs:
    unique.setdefault(output["relativePath"], output)
  router_rel = "src/app/generated_routers.py"
  router_path = _safe_target(root, router_rel)
  existing_router = router_path.read_text(encoding="utf-8") if router_path.exists() else ""
  unique[router_rel] = {
    "relativePath": router_rel,
    "content": _router_content(plan["contexts"], existing_router),
    "template": "generated-router",
    "layer": "router-index",
    "entity": None,
    "module": None,
  }
  return list(unique.values())


def _load_prior_manifest(path: Path) -> dict:
  if not path.exists():
    return {}
  try:
    data = json.loads(path.read_text(encoding="utf-8"))
    return data if data.get("schemaVersion") == 2 and isinstance(data.get("files"), dict) else {}
  except (OSError, json.JSONDecodeError):
    return {}


def execute_generation(
  plan: dict,
  feature_dir: Path,
  spec_path: Path,
  *,
  dry_run: bool = False,
) -> dict:
  root = repo_root()
  manifest_path = feature_dir / "generated" / "codegen.manifest.json"
  handoff_path = feature_dir / "generated" / "HANDOFF.md"
  _reject_symlinks(manifest_path)
  _reject_symlinks(handoff_path)
  prior = _load_prior_manifest(manifest_path)
  prior_files = prior.get("files") or {}
  outputs = _planned_outputs(plan)
  decisions: list[dict] = []

  for output in outputs:
    rel = output["relativePath"]
    target = _safe_target(root, rel)
    expected_hash = _sha256(output["content"])
    if not target.exists():
      status = "would-write"
    else:
      existing_hash = hashlib.sha256(target.read_bytes()).hexdigest()
      if existing_hash == expected_hash:
        status = "unchanged"
      elif prior_files.get(rel, {}).get("sha256") == existing_hash:
        status = "would-write"
      elif plan["force"]:
        status = "would-force"
      else:
        status = "conflict"
    decisions.append({**output, "target": target, "sha256": expected_hash, "status": status})

  conflicts = [item for item in decisions if item["status"] == "conflict"]
  if conflicts:
    return {"decisions": decisions, "conflicts": conflicts, "manifestPath": manifest_path}

  manifest = {
    "schemaVersion": 2,
    "packageVersion": _package_version(),
    "generator": GENERATOR,
    "spec": str(spec_path),
    "entities": [
      {
        "module": ctx["module"],
        "modulePackage": ctx["module_package"],
        "entity": ctx["entity"],
        "entityPackage": ctx["entity_snake"],
        "routePrefix": ctx["route_prefix"],
      }
      for ctx in plan["contexts"]
    ],
    "files": {
      item["relativePath"]: {
        "sha256": item["sha256"],
        "template": item["template"],
        "layer": item["layer"],
        "entity": item["entity"],
        "module": item["module"],
      }
      for item in decisions
    },
  }
  if not dry_run:
    for item in decisions:
      if item["status"] != "unchanged":
        item["target"].parent.mkdir(parents=True, exist_ok=True)
        item["target"].write_text(item["content"], encoding="utf-8")
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    handoff_path.write_text(render_handoff(plan, spec_path), encoding="utf-8")
  return {
    "decisions": decisions,
    "conflicts": [],
    "manifestPath": manifest_path,
    "handoffPath": handoff_path,
    "manifest": manifest,
  }


def render_handoff(plan: dict, spec_path: Path) -> str:
  lines = ["# fast-gen HANDOFF", "", f"- Spec: `{spec_path}`", "", "## Entities", ""]
  lines.extend(
    f"- `{ctx['module']}.{ctx['entity']}` → `{ctx['route_prefix']}`"
    for ctx in plan["contexts"]
  )
  lines.extend([
    "",
    "## Verify",
    "",
    "```bash",
    "PYTHONPATH=src .venv/bin/pytest -q",
    "PYTHONPATH=src .venv/bin/uvicorn app.main:app --port 4000 --app-dir src",
    "```",
    "",
  ])
  return "\n".join(lines)


def export_openapi(feature_dir: Path, _spec: dict) -> Path:
  import yaml
  from app.main import app

  schema = app.openapi()
  out_path = feature_dir / "backend" / "02-openapi.yaml"
  out_path.parent.mkdir(parents=True, exist_ok=True)
  out_path.write_text(yaml.dump(schema, sort_keys=False, allow_unicode=True), encoding="utf-8")
  return out_path
