from __future__ import annotations

import json
import os
import re
from datetime import UTC, datetime
from pathlib import Path

from fast_gen.plan import render_template


def repo_root() -> Path:
  target = os.environ.get("CODEGENKIT_ROOT")
  if not target:
    raise RuntimeError("CODEGENKIT_ROOT is required for the FastAPI adapter")
  return Path(target).resolve()


def write_outputs(plan: dict, *, dry_run: bool = False) -> tuple[list[str], list[dict]]:
  root = repo_root()
  written: list[str] = []
  skipped = list(plan["skipped"])

  for file in plan["files"]:
    rel = file["relativePath"]
    content = render_template(file["template"], plan["ctx"])
    if dry_run:
      written.append(rel)
      continue
    abs_path = root / rel
    abs_path.parent.mkdir(parents=True, exist_ok=True)
    abs_path.write_text(content, encoding="utf-8")
    written.append(rel)

  if not dry_run:
    _write_package_inits(plan)
    _update_generated_routers(plan)

  return written, skipped


def _write_package_inits(plan: dict) -> None:
  ctx = plan["ctx"]
  root = repo_root()
  module_dir = root / "src" / "app" / "modules" / ctx["module_kebab"]
  entity_dir = module_dir / ctx["entity_snake"]
  for folder in [module_dir, entity_dir, entity_dir / "schemas", entity_dir / "services", entity_dir / "presenters"]:
    folder.mkdir(parents=True, exist_ok=True)
    init_file = folder / "__init__.py"
    if not init_file.exists():
      init_file.write_text('"""Generated module package."""\n', encoding="utf-8")


def _update_generated_routers(plan: dict) -> None:
  ctx = plan["ctx"]
  root = repo_root()
  routers_file = root / "src" / "app" / "generated_routers.py"
  import_line = (
    f"from app.modules.{ctx['module_kebab']}.{ctx['entity_snake']}.router import "
    f"router as {ctx['module_kebab'].replace('-', '_')}_{ctx['entity_snake']}_router"
  )

  imports: list[str] = []
  if routers_file.exists():
    for line in routers_file.read_text(encoding="utf-8").splitlines():
      if line.startswith("from app.modules.") and " import " in line:
        imports.append(line)

  if import_line not in imports:
    imports.append(import_line)

  aliases = [line.split(" as ")[-1].strip() for line in imports]
  body = [
    '"""Auto-generated by fast-gen — do not edit manually."""',
    "",
    "from fastapi import APIRouter",
    "",
    *imports,
    "",
    "ROUTERS: list[APIRouter] = [",
    *[f"  {alias}," for alias in aliases],
    "]",
    "",
  ]
  routers_file.write_text("\n".join(body), encoding="utf-8")


def write_manifest(feature_dir: Path, plan: dict, spec_path: Path, *, dry_run: bool = False, written: list[str] | None = None) -> dict:
  written = written or []
  manifest = {
    "spec": str(spec_path),
    "module": plan["ctx"]["module"],
    "entity": plan["ctx"]["entity"],
    "profile": plan["ctx"]["profile"],
    "files": plan["files"],
    "written": written,
    "skipped": plan["skipped"],
    "generatedAt": datetime.now(UTC).isoformat(),
  }
  out_dir = feature_dir / "generated"
  manifest_path = out_dir / "codegen.manifest.json"
  handoff_path = out_dir / "HANDOFF.md"

  if not dry_run:
    out_dir.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    handoff_path.write_text(render_handoff(plan, spec_path), encoding="utf-8")

  return {"manifestPath": manifest_path, "handoffPath": handoff_path, "manifest": manifest}


def render_handoff(plan: dict, spec_path: Path) -> str:
  ctx = plan["ctx"]
  return "\n".join(
    [
      f"# fast-gen HANDOFF — {ctx['entity_pascal']}",
      "",
      f"- Spec: `{spec_path}`",
      f"- Module: `{ctx['module']}` / entity `{ctx['entity']}`",
      f"- Route prefix: `{ctx['route_prefix']}`",
      "",
      "## Verify",
      "",
      "```bash",
      "cd /path/to/current-fastapi-repo",
      "PYTHONPATH=tools:src .venv/bin/pytest -q",
      "PYTHONPATH=tools:src .venv/bin/uvicorn app.main:app --port 4000 --app-dir src",
      "```",
      "",
    ]
  )


def export_openapi(feature_dir: Path, _spec: dict) -> Path:
  import yaml
  from app.main import app

  schema = app.openapi()
  out_path = feature_dir / "backend" / "02-openapi.yaml"
  out_path.parent.mkdir(parents=True, exist_ok=True)
  out_path.write_text(yaml.dump(schema, sort_keys=False, allow_unicode=True), encoding="utf-8")
  return out_path
